---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: discovery
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./k3d-cluster/my-cluster/discovery/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: simple
  targetNamespace: default

