---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: simple
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/jangabrielsson/cluster-play/tree/main/k3d-cluster/my-cluster/

