---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: simple
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./simple/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: simple
  targetNamespace: default

